[tool.poetry]
name = "dspy-pipeline"
version = "0.1.0"
description = "Dspy pipeline package"
authors = ["Your Name <your.email@example.com>"]

[tool.poetry.scripts]
dspy-pipeline = "dspy_pipeline.main:main"
