[tool.poetry]
name = "autodev-pipeline"
version = "0.1.0"
description = "Dspy pipeline package"
authors = ["Tom Dörr <tomdoerr96@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
rich = "^13.0.0"

[tool.poetry.scripts]
audev = "dspy_pipeline.main:main"
