[tool.poetry]
name = "dspy-pipeline"
version = "0.1.0"
description = "Dspy pipeline package"
authors = ["Tom Dörr <tomdoerr96@gmail.com>"]

[tool.poetry.scripts]
dspy-pipeline = "dspy_pipeline.main:main"
